version: '3.3'

services:
  web:
    image: deejeezz/skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
    - "80:8080"
    restart: always
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
