version: '3.3'

services:
  web:
#    image: deejeezz/skypro:local
    build: .
    ports:
    - "80:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
